[package]
name = "galc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8.0"
itertools = "0.10.3"
unicode-ident = "1.0.2"
common_macros = "0.1.1"
structopt = "0.3"
num = "0.4.0"
